# Generated by Django 3.0.6 on 2020-08-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='name',
        ),
    ]
